# Creating Array from list

In [1]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([[1,2,3,4],[4,6,7,8]])

In [2]:
print("First Array : ",x)
print("Second Array : ",y)

First Array :  [1 2 3 4 5]
Second Array :  [[1 2 3 4]
 [4 6 7 8]]


In [3]:
# Finding dimension of array
print(x.ndim)
print(y.ndim)

1
2


## Zeros

In [4]:
x_0_array = np.zeros(4)
x_0_array1=np.zeros((3,4))
print("First Array : ",x_0_array)
print("Second Array : ",x_0_array1)

First Array :  [0. 0. 0. 0.]
Second Array :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [5]:
x_1_array = np.ones(4)
x_1_array1=np.ones((3,4))
print("First Array : ",x_1_array)
print("Second Array : ",x_1_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Creating Empty Array
    It store previous memory data

In [6]:
x_empty_array = np.empty(4)
x_empty_array1=np.empty((3,4))
print("First Array : ",x_empty_array)
print("Second Array : ",x_empty_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Range 

In [7]:
x_arange_array = np.arange(4)
print("First Array : ",x_arange_array)

First Array :  [0 1 2 3]


## Array diagonaly element filled with 1's

In [8]:
x_eye_array = np.eye(5)
print(x_eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
x_eye_array1 = np.eye(3,5)
print(x_eye_array1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## linspace
    This metod create an array of equal spacing
    
*** STNTAX ***
linspace(START,END,num=Number_of_element)

In [10]:
ar_lin = np.linspace(1,10,num=3)
print(ar_lin)

[ 1.   5.5 10. ]


# Random

## Rand()
This function genaerte array of random number passed as a parameters. Number will be between 0 to 1. 

In [11]:
rand_arrray = np.random.rand(5)
print(rand_arrray)
rand_arrray1 = np.random.rand(3,5)
print(rand_arrray1)

[0.81259786 0.63791492 0.83763795 0.5351586  0.35973581]
[[0.46850488 0.47409189 0.2828046  0.57319003 0.92813311]
 [0.26489403 0.62568741 0.44695717 0.79406547 0.12647741]
 [0.19774181 0.09632605 0.10415421 0.80951141 0.39657934]]


## Randn()
This return positive and negative both.

In [12]:
randn_arrray = np.random.randn(5)
print(randn_arrray)
randn_arrray1 = np.random.randn(3,5)
print(randn_arrray1)

[ 0.49161527 -1.54185213 -0.87892533 -1.58311535  0.99220994]
[[ 1.82432338  0.97290116 -0.03267761 -0.31293011 -1.7852309 ]
 [ 0.13919697  0.22855189  0.77831848  1.66574463 -1.05690524]
 [ 0.39327198 -0.07350091  0.213963   -1.48471767 -0.98600187]]


## Ranf()
This function return float number between [0.0 to 1.0)

In [13]:
ranf_arrray = np.random.ranf(5)
print(ranf_arrray)

[0.16795723 0.04227868 0.34248131 0.32753747 0.11754421]


## randint()
This function return number between a given range
SYNTAX : np.random.randint(min,max,number_of_values)

In [14]:
randint_arrray = np.random.randint(3,40,5)
print(randint_arrray)

[ 5 17  8 10 27]


# DataType In Numpy Array
- bool_ : boolean true false
- int_
- int8
- int16
- int32
- int64
- uint8 : Unsignedinteger (0 to 255)
- float_
- float32
- complex_ : for complex number

In [15]:
array = np.array([5,6,3,5])
print(array.dtype)

int64


In [16]:
array = np.array([5.9,6.0,3.4,5.5])
print(array.dtype)

float64


In [17]:
## Conversion of data type
array_conver = np.array([5,6,7,8],dtype = np.int8)
print(array_conver.dtype)

int8


In [18]:
## Conversion of data type
array_conver = np.array([5,6,7,8],dtype = "f")
print(array_conver.dtype)

float32


In [19]:
## Conversion of data type
array_conver = np.array([5,6,7,8])
new_array_converted = np.float32(array_conver)
print(new_array_converted.dtype)

float32


In [20]:
## Conversion of data type
array_conver = np.array([5,6,7,8])
new_array_converted = array_conver.astype(float)
print(new_array_converted.dtype)

float64


# Arithmetic Operation in Numpy array
- (a+b) : np.add(a,b)
- (a-b) : np.subtract(a,b)
- (a*b) : np.multiply(a,b)
- (a/b) : np.divide(a,b)
- (a%b) : np.mod(a,b)
- (a**b) : np.power(a,b)
- (1/a) : np.reciprocal(a)

In [21]:
c = np.arange(2,5)
d = np.arange(2,5)
print(c,d)
print(np.add(c,d))
print(c+d)
print(c+7)
# These opertion can be performed for 2D

[2 3 4] [2 3 4]
[4 6 8]
[4 6 8]
[ 9 10 11]


## Arithmetic function in numpy array
- np.min(x)
- np.max(x)
- np.argmin(x) : return min index
- np.argmax(x) : return max index
- np.sqrt(x)
- np.sin(x)
- np.cos(x)
- np.cumsum(x)

In [22]:
mx = np.arange(5,9)
yx =np.array([[1,2,3,4],[4,6,7,8]])
print(mx)
print(np.max(mx))
print(np.max(yx,axis=1))

[5 6 7 8]
8
[4 8]


# Shape

In [23]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print(array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
a= np.array([1,2,3,4],ndmin=4)
print(a)
print(a.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


# Reshape

In [25]:
m= np.array([3,4,5,6,7,8,9,5])
# new_m=m.reshape(2,3)
new1_m=m.reshape(2,2,2)
print(new1_m)
d1 = new1_m.reshape(-1)
print(d1)

[[[3 4]
  [5 6]]

 [[7 8]
  [9 5]]]
[3 4 5 6 7 8 9 5]


# Broadcasting

In [26]:
b1=np.array([1,2,3])
b1_sh=b1.reshape(1,3)
b2=np.array([4,4,6])
b2_sh=b2.reshape(3,1)
print(b1_sh, b2_sh) 
print(b1_sh + b2_sh)

[[1 2 3]] [[4]
 [4]
 [6]]
[[5 6 7]
 [5 6 7]
 [7 8 9]]


# Indexing and slicing in numpy

In [27]:
iarray = np.array([1,2,3,4,5,6,7,8,9,10,11,13])
new_i_array = iarray.reshape(2,3,2)
print(new_i_array)
print(new_i_array[0][2][0])
print(new_i_array[0,2,0])

#Slicing
print(new_i_array[0,0,0:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 13]]]
5
5
[1 2]


# Iteration in array

## nditer()

In [28]:
a=np.array([[[1,2,3],[4,5,6]]])
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


## ndenumerate()

In [29]:
a=np.array([[[1,2,3],[4,5,6]]])
for i,d in np.ndenumerate(a):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6


## Copy vs View

In [30]:
v=np.array([1,2,3,4])
k=v.copy()
print(k)

v1=np.array([1,2,3,4])
vView=v1.copy()
print(vView)

[1 2 3 4]
[1 2 3 4]


## Diffrence b/w view and copy

- Copy
  - Copy owns the data
  - Copy of array is new array
- View
  - View doesn't own the data.
  - View is the original array.
  - Any changes in view affect the original array.

## Join and Splits function in numpy array

In [31]:
a=np.array([1,2,3])
b=np.array([4,5,6])
ab=np.concatenate((a,b))
print(ab)

[1 2 3 4 5 6]


In [32]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
ab=np.concatenate((a,b),axis=1)
print(ab)

[[1 2 5 6]
 [3 4 7 8]]


In [33]:
a=np.array([1,2,3])
b=np.array([4,5,6])
ab=np.stack((a,b))
ab1=np.hstack((a,b)) #row
ab2=np.vstack((a,b)) #col
ab3=np.dstack((a,b)) #heights
print(ab)
print(ab1)
print(ab2)
print(ab3)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [34]:
v=np.array([1,2,3,4,5,6])
ar=np.array_split(v,3)
print(ar)
v1=np.array([[1,2],[3,4],[5,6]])
ar1=np.array_split(v,3)
print(ar1)
ar2=np.array_split(v,3,axis=0)
print(ar2)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


## Num py array function

## Search Array

In [35]:
a=np.array([1,2,3,4,5,6,7])
print(np.where(a==4))

(array([3]),)


In [36]:
a=np.array([1,2,3,4,5,6])
x=np.searchsorted(a,4.5)
print(x)
#also we can pass attribute side="right" side="left" for the index

4


In [37]:
a=np.array([1,2,3,4,5,6])
x=np.searchsorted(a,[4.5,8.6,2.1])
print(x)

[4 6 2]


## Sort

In [38]:
a=np.random.rand(5)
print(a)
print(np.sort(a))

[0.20200574 0.76235188 0.7890303  0.22611048 0.55399247]
[0.20200574 0.22611048 0.55399247 0.76235188 0.7890303 ]


## Filter array

In [39]:
kh=np.array([1,2,3,4,5,6])
bf=[True,False,False,True,True,False]
k=kh[bf]
print(k)

[1 4 5]


## Arithmetic Function
- Shuffle
- Unique
- Resize
- Flatten
- Ravel

In [40]:
a=np.array([1,2,3,4,5,6])
np.random.shuffle(a)
print(a)

[5 1 2 4 3 6]


In [41]:
a=np.array([1,2,3,3,4,2,2,4,6,7,6,4,5,6])
k=np.unique(a)
ki=np.unique(a,return_index=True,return_counts=True)
print(k)
print(ki)

[1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7]), array([ 0,  1,  2,  4, 12,  8,  9]), array([1, 3, 2, 3, 1, 3, 1]))


In [42]:
a=np.array([1,2,3,3,4,2,2,4,6,7,6,4,5,6])
k=np.resize(a,(7,2))
print(k)

[[1 2]
 [3 3]
 [4 2]
 [2 4]
 [6 7]
 [6 4]
 [5 6]]


## Insert

In [43]:
a=np.array([1,2,3,3,4,2,2,4,6,7,6,4,5,6])
k=np.insert(a,2,70)
print(k)

[ 1  2 70  3  3  4  2  2  4  6  7  6  4  5  6]


In [44]:
v1=np.array([[1,2],[3,4],[5,6]])
k=np.insert(v1,1,2,axis=1)
print(k)

[[1 2 2]
 [3 2 4]
 [5 2 6]]


In [45]:
v1=np.array([[1,2],[3,4],[5,6]])
k=np.append(v1,[[2,3]],axis=0)
print(k)

[[1 2]
 [3 4]
 [5 6]
 [2 3]]


In [46]:
v1=np.array([[1,2],[3,4],[5,6]])
k=np.delete(v1,0,axis=0)
print(k)

[[3 4]
 [5 6]]


## Matrix In Numpy

In [50]:
mat1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat1+mat2)
print(mat1*mat2)
print(mat1.dot(mat2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## matrix Functions
- Transpose
- Swapaxes
- Inverse
- Power
- Determinate


In [52]:
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.transpose(mat))
print(mat.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [54]:
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.swapaxes(mat,1,0)) #(matrix_name,axis,intoaxis)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [56]:
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.inv(mat)) 

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [59]:
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.matrix_power(mat,2)) #(matrix_nmae,power)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [60]:
mat = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.det(mat))

-9.51619735392994e-16
