# Creating Array from list

In [5]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([[1,2,3,4],[4,6,7,8]])

In [8]:
print("First Array : ",x)
print("Second Array : ",y)

[1 2 3 4 5]
[[1 2 3 4]
 [4 6 7 8]]


In [10]:
# Finding dimension of array
print(x.ndim)
print(y.ndim)

1
2


## Zeros

In [13]:
x_0_array = np.zeros(4)
x_0_array1=np.zeros((3,4))
print("First Array : ",x_0_array)
print("Second Array : ",x_0_array1)

First Array :  [0. 0. 0. 0.]
Second Array :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [15]:
x_1_array = np.ones(4)
x_1_array1=np.ones((3,4))
print("First Array : ",x_1_array)
print("Second Array : ",x_1_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Creating Empty Array
    It store previous memory data

In [16]:
x_empty_array = np.empty(4)
x_empty_array1=np.empty((3,4))
print("First Array : ",x_empty_array)
print("Second Array : ",x_empty_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Range 

In [31]:
x_arange_array = np.arange(4)
print("First Array : ",x_arange_array)

First Array :  [0 1 2 3]


## Array diagonaly element filled with 1's

In [25]:
x_eye_array = np.eye(5)
print(x_eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
x_eye_array1 = np.eye(3,5)
print(x_eye_array1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## linspace
    This metod create an array of equal spacing
    
*** STNTAX ***
linspace(START,END,num=Number_of_element)

In [32]:
ar_lin = np.linspace(1,10,num=3)
print(ar_lin)

[ 1.   5.5 10. ]
