# Creating Array from list

In [1]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([[1,2,3,4],[4,6,7,8]])

In [2]:
print("First Array : ",x)
print("Second Array : ",y)

First Array :  [1 2 3 4 5]
Second Array :  [[1 2 3 4]
 [4 6 7 8]]


In [3]:
# Finding dimension of array
print(x.ndim)
print(y.ndim)

1
2


## Zeros

In [4]:
x_0_array = np.zeros(4)
x_0_array1=np.zeros((3,4))
print("First Array : ",x_0_array)
print("Second Array : ",x_0_array1)

First Array :  [0. 0. 0. 0.]
Second Array :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [5]:
x_1_array = np.ones(4)
x_1_array1=np.ones((3,4))
print("First Array : ",x_1_array)
print("Second Array : ",x_1_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Creating Empty Array
    It store previous memory data

In [6]:
x_empty_array = np.empty(4)
x_empty_array1=np.empty((3,4))
print("First Array : ",x_empty_array)
print("Second Array : ",x_empty_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Range 

In [7]:
x_arange_array = np.arange(4)
print("First Array : ",x_arange_array)

First Array :  [0 1 2 3]


## Array diagonaly element filled with 1's

In [8]:
x_eye_array = np.eye(5)
print(x_eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
x_eye_array1 = np.eye(3,5)
print(x_eye_array1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## linspace
    This metod create an array of equal spacing
    
*** STNTAX ***
linspace(START,END,num=Number_of_element)

In [10]:
ar_lin = np.linspace(1,10,num=3)
print(ar_lin)

[ 1.   5.5 10. ]


# Random

## Rand()
This function genaerte array of random number passed as a parameters. Number will be between 0 to 1. 

In [11]:
rand_arrray = np.random.rand(5)
print(rand_arrray)
rand_arrray1 = np.random.rand(3,5)
print(rand_arrray1)

[0.08306801 0.78402488 0.29501201 0.47103133 0.96082011]
[[0.56787616 0.1813776  0.93796354 0.40851294 0.90579041]
 [0.56694253 0.19215411 0.10405968 0.21977555 0.78683679]
 [0.28266024 0.45500192 0.55833712 0.1287036  0.09968348]]


## Randn()
This return positive and negative both.

In [12]:
randn_arrray = np.random.randn(5)
print(randn_arrray)
randn_arrray1 = np.random.randn(3,5)
print(randn_arrray1)

[-0.92634387 -0.22899181  0.37471574 -0.34643244  0.03420805]
[[-0.05685499  0.36857641 -1.56128087  1.94196725 -0.37386161]
 [-0.97284942 -1.15771768  1.28093896 -0.14161895  2.10882839]
 [-1.27575062  2.09676661 -0.27594671  0.08555579  0.88371021]]


## Ranf()
This function return float number between [0.0 to 1.0)

In [13]:
ranf_arrray = np.random.ranf(5)
print(ranf_arrray)

[0.32689447 0.97677268 0.47637418 0.07443158 0.34016842]


## randint()
This function return number between a given range
SYNTAX : np.random.randint(min,max,number_of_values)

In [14]:
randint_arrray = np.random.randint(3,40,5)
print(randint_arrray)

[34 10 39 31 28]


# DataType In Numpy Array
- bool_ : boolean true false
- int_
- int8
- int16
- int32
- int64
- uint8 : Unsignedinteger (0 to 255)
- float_
- float32
- complex_ : for complex number

In [15]:
array = np.array([5,6,3,5])
print(array.dtype)

int64


In [16]:
array = np.array([5.9,6.0,3.4,5.5])
print(array.dtype)

float64


In [17]:
## Conversion of data type
array_conver = np.array([5,6,7,8],dtype = np.int8)
print(array_conver.dtype)

int8


In [18]:
## Conversion of data type
array_conver = np.array([5,6,7,8],dtype = "f")
print(array_conver.dtype)

float32


In [19]:
## Conversion of data type
array_conver = np.array([5,6,7,8])
new_array_converted = np.float32(array_conver)
print(new_array_converted.dtype)

float32


In [20]:
## Conversion of data type
array_conver = np.array([5,6,7,8])
new_array_converted = array_conver.astype(float)
print(new_array_converted.dtype)

float64


# Arithmetic Operation in Numpy array
- (a+b) : np.add(a,b)
- (a-b) : np.subtract(a,b)
- (a*b) : np.multiply(a,b)
- (a/b) : np.divide(a,b)
- (a%b) : np.mod(a,b)
- (a**b) : np.power(a,b)
- (1/a) : np.reciprocal(a)

In [21]:
c = np.arange(2,5)
d = np.arange(2,5)
print(c,d)
print(np.add(c,d))
print(c+d)
print(c+7)
# These opertion can be performed for 2D

[2 3 4] [2 3 4]
[4 6 8]
[4 6 8]
[ 9 10 11]


## Arithmetic function in numpy array
- np.min(x)
- np.max(x)
- np.argmin(x) : return min index
- np.argmax(x) : return max index
- np.sqrt(x)
- np.sin(x)
- np.cos(x)
- np.cumsum(x)

In [22]:
mx = np.arange(5,9)
yx =np.array([[1,2,3,4],[4,6,7,8]])
print(mx)
print(np.max(mx))
print(np.max(yx,axis=1))

[5 6 7 8]
8
[4 8]


# Shape

In [28]:
array = np.array([[1,2,3],[4,5,6]])
print(array)
print(array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [29]:
a= np.array([1,2,3,4],ndmin=4)
print(a)
print(a.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


# Reshape

In [39]:
m= np.array([3,4,5,6,7,8,9,5])
# new_m=m.reshape(2,3)
new1_m=m.reshape(2,2,2)
print(new1_m)
d1 = new1_m.reshape(-1)
print(d1)

[[[3 4]
  [5 6]]

 [[7 8]
  [9 5]]]
[3 4 5 6 7 8 9 5]


# Broadcasting

In [43]:
b1=np.array([1,2,3])
b1_sh=b1.reshape(1,3)
b2=np.array([4,4,6])
b2_sh=b2.reshape(3,1)
print(b1_sh, b2_sh) 
print(b1_sh + b2_sh)

[[1 2 3]] [[4]
 [4]
 [6]]
[[5 6 7]
 [5 6 7]
 [7 8 9]]


# Indexing and slicing in numpy

In [52]:
iarray = np.array([1,2,3,4,5,6,7,8,9,10,11,13])
new_i_array = iarray.reshape(2,3,2)
print(new_i_array)
print(new_i_array[0][2][0])
print(new_i_array[0,2,0])

#Slicing
print(new_i_array[0,0,0:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 13]]]
5
5
[1 2]


# Iteration in array

## nditer()

In [54]:
a=np.array([[[1,2,3],[4,5,6]]])
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6


## ndenumerate()

In [58]:
a=np.array([[[1,2,3],[4,5,6]]])
for i,d in np.ndenumerate(a):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6


## Copy vs View

In [60]:
v=np.array([1,2,3,4])
k=v.copy()
print(k)

v1=np.array([1,2,3,4])
vView=v1.copy()
print(vView)

[1 2 3 4]
[1 2 3 4]


## Diffrence b/w view and copy

- Copy
  - Copy owns the data
  - Copy of array is new array
- View
  - View doesn't own the data.
  - View is the original array.
  - Any changes in view affect the original array.

## Join and Splits function in numpy array

In [62]:
a=np.array([1,2,3])
b=np.array([4,5,6])
ab=np.concatenate((a,b))
print(ab)

[1 2 3 4 5 6]


In [66]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
ab=np.concatenate((a,b),axis=1)
print(ab)

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
a=np.array([1,2,3])
b=np.array([4,5,6])
ab=np.stack((a,b))
ab1=np.hstack((a,b)) #row
ab2=np.vstack((a,b)) #col
ab3=np.dstack((a,b)) #heights
print(ab)
print(ab1)
print(ab2)
print(ab3)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [73]:
v=np.array([1,2,3,4,5,6])
ar=np.array_split(v,3)
print(ar)
v1=np.array([[1,2],[3,4],[5,6]])
ar1=np.array_split(v,3)
print(ar1)
ar2=np.array_split(v,3,axis=0)
print(ar2)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


## Num py array function

## Search Array

In [74]:
a=np.array([1,2,3,4,5,6,7])
print(np.where(a==4))

(array([3]),)


In [78]:
a=np.array([1,2,3,4,5,6])
x=np.searchsorted(a,4.5)
print(x)
#also we can pass attribute side="right" side="left" for the index

4


In [79]:
a=np.array([1,2,3,4,5,6])
x=np.searchsorted(a,[4.5,8.6,2.1])
print(x)

[4 6 2]


## Sort

In [80]:
a=np.random.rand(5)
print(a)
print(np.sort(a))

[0.68297531 0.28405876 0.98372975 0.0999766  0.34082982]
[0.0999766  0.28405876 0.34082982 0.68297531 0.98372975]


## Filter array

In [81]:
kh=np.array([1,2,3,4,5,6])
bf=[True,False,False,True,True,False]
k=kh[bf]
print(k)

[1 4 5]
