# Creating Array from list

In [1]:
import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([[1,2,3,4],[4,6,7,8]])

In [2]:
print("First Array : ",x)
print("Second Array : ",y)

First Array :  [1 2 3 4 5]
Second Array :  [[1 2 3 4]
 [4 6 7 8]]


In [3]:
# Finding dimension of array
print(x.ndim)
print(y.ndim)

1
2


## Zeros

In [4]:
x_0_array = np.zeros(4)
x_0_array1=np.zeros((3,4))
print("First Array : ",x_0_array)
print("Second Array : ",x_0_array1)

First Array :  [0. 0. 0. 0.]
Second Array :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [5]:
x_1_array = np.ones(4)
x_1_array1=np.ones((3,4))
print("First Array : ",x_1_array)
print("Second Array : ",x_1_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Creating Empty Array
    It store previous memory data

In [6]:
x_empty_array = np.empty(4)
x_empty_array1=np.empty((3,4))
print("First Array : ",x_empty_array)
print("Second Array : ",x_empty_array1)

First Array :  [1. 1. 1. 1.]
Second Array :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Range 

In [7]:
x_arange_array = np.arange(4)
print("First Array : ",x_arange_array)

First Array :  [0 1 2 3]


## Array diagonaly element filled with 1's

In [8]:
x_eye_array = np.eye(5)
print(x_eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
x_eye_array1 = np.eye(3,5)
print(x_eye_array1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## linspace
    This metod create an array of equal spacing
    
*** STNTAX ***
linspace(START,END,num=Number_of_element)

In [10]:
ar_lin = np.linspace(1,10,num=3)
print(ar_lin)

[ 1.   5.5 10. ]


# Random

## Rand()
This function genaerte array of random number passed as a parameters. Number will be between 0 to 1. 

In [12]:
rand_arrray = np.random.rand(5)
print(rand_arrray)
rand_arrray1 = np.random.rand(3,5)
print(rand_arrray1)

[0.87656545 0.14460214 0.90298137 0.16950715 0.05112984]
[[0.05063701 0.76473293 0.65357045 0.21174825 0.05089358]
 [0.47537815 0.88882111 0.89215546 0.67997386 0.97790361]
 [0.10890151 0.80968716 0.41287133 0.66704858 0.62421892]]


## Randn()
This return positive and negative both.

In [14]:
randn_arrray = np.random.randn(5)
print(randn_arrray)
randn_arrray1 = np.random.randn(3,5)
print(randn_arrray1)

[-0.89988607  1.53414749 -0.34033864 -0.37979743  0.59367881]
[[-0.40595036  0.75102469 -1.1566574   0.32962331 -1.50206693]
 [-0.34887899  0.2040458   0.73488242 -1.09554913  0.84574467]
 [ 0.33807276  0.16002551  0.51249966  1.50950648  0.77695714]]


## Ranf()
This function return float number between [0.0 to 1.0)

In [17]:
ranf_arrray = np.random.ranf(5)
print(ranf_arrray)

[0.75567145 0.21823029 0.98677189 0.96672285 0.17569175]


## randint()
This function return number between a given range
SYNTAX : np.random.randint(min,max,number_of_values)

In [22]:
randint_arrray = np.random.randint(3,40,5)
print(randint_arrray)

[32 15 16 14 34]


# DataType In Numpy Array
- bool_ : boolean true false
- int_
- int8
- int16
- int32
- int64
- uint8 : Unsignedinteger (0 to 255)
- float_
- float32
- complex_ : for complex number

In [23]:
array = np.array([5,6,3,5])
print(array.dtype)

int64


In [24]:
array = np.array([5.9,6.0,3.4,5.5])
print(array.dtype)

float64


In [29]:
## Conversion of data type
array_conver = np.array([5,6,7,8],dtype = np.int8)
print(array_conver.dtype)

int8


In [30]:
## Conversion of data type
array_conver = np.array([5,6,7,8],dtype = "f")
print(array_conver.dtype)

float32


In [31]:
## Conversion of data type
array_conver = np.array([5,6,7,8])
new_array_converted = np.float32(array_conver)
print(new_array_converted.dtype)

float32


In [33]:
## Conversion of data type
array_conver = np.array([5,6,7,8])
new_array_converted = array_conver.astype(float)
print(new_array_converted.dtype)

float64


# Arithmetic Operation in Numpy array
- (a+b) : np.add(a,b)
- (a-b) : np.subtract(a,b)
- (a*b) : np.multiply(a,b)
- (a/b) : np.divide(a,b)
- (a%b) : np.mod(a,b)
- (a**b) : np.power(a,b)
- (1/a) : np.reciprocal(a)

In [40]:
c = np.arange(2,5)
d = np.arange(2,5)
print(c,d)
print(np.add(c,d))
print(c+d)
print(c+7)
# These opertion can be performed for 2D

[2 3 4] [2 3 4]
[4 6 8]
[4 6 8]
[ 9 10 11]


## Arithmetic function in numpy array
- np.min(x)
- np.max(x)
- np.argmin(x) : return min index
- np.argmax(x) : return max index
- np.sqrt(x)
- np.sin(x)
- np.cos(x)
- np.cumsum(x)

In [47]:
mx = np.arange(5,9)
yx =np.array([[1,2,3,4],[4,6,7,8]])
print(mx)
print(np.max(mx))
print(np.max(yx,axis=1))

[5 6 7 8]
8
[4 8]
